[build]
builder = "nixpacks"
buildCommand = "pnpm install --no-frozen-lockfile && pnpm run build"

[deploy]
startCommand = "caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"
healthcheckPath = "/"