import { User, SkillListing, Session, Review } from './types';

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  avatar: 'https://images.unsplash.com/photo-1655249481446-25d575f1c054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBidXNpbmVzcyUyMHBlcnNvbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc3MzgyODg4OXww&ixlib=rb-4.1.0&q=80&w=1080',
  bio: 'Full-stack developer passionate about teaching and learning new technologies. I believe in skill sharing and community growth.',
  rating: 4.8,
  reviewsCount: 47,
  skills: [
    { id: 's1', name: 'React Development', level: 'Expert', yearsOfExperience: 5 },
    { id: 's2', name: 'UI/UX Design', level: 'Intermediate', yearsOfExperience: 3 },
    { id: 's3', name: 'Python Programming', level: 'Expert', yearsOfExperience: 6 },
    { id: 's4', name: 'Digital Marketing', level: 'Beginner', yearsOfExperience: 1 },
  ],
};

export const skillListings: SkillListing[] = [
  {
    id: 'listing-1',
    title: 'Advanced React & TypeScript Development',
    description: 'Learn modern React patterns, hooks, TypeScript integration, and state management with real-world projects.',
    category: 'Programming',
    price: 45,
    swapAvailable: true,
    userId: 'user-2',
    userName: 'Sarah Chen',
    userAvatar: 'https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwcHJvZmVzc2lvbmFsJTIwaGVhZHNob3R8ZW58MXx8fHwxNzczODM2NjU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.9,
    type: 'offer',
    createdAt: '2026-03-18',
  },
  {
    id: 'listing-2',
    title: 'Guitar Lessons - Acoustic & Electric',
    description: 'From beginner chords to advanced techniques. 10 years of teaching experience.',
    category: 'Music',
    price: 30,
    swapAvailable: true,
    userId: 'user-3',
    userName: 'Michael Torres',
    userAvatar: 'https://images.unsplash.com/photo-1605298046196-e205d0d699d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHNtaWxpbmd8ZW58MXx8fHwxNzczOTMyNjIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.7,
    type: 'offer',
    createdAt: '2026-03-17',
  },
  {
    id: 'listing-3',
    title: 'Looking for French Language Teacher',
    description: 'Need someone to help me reach conversational level in French. Willing to swap with English or Spanish lessons.',
    category: 'Languages',
    swapAvailable: true,
    userId: 'user-4',
    userName: 'Emma Rodriguez',
    userAvatar: 'https://images.unsplash.com/photo-1687575635557-a3f3ed535b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGNyZWF0aXZlJTIwcHJvZmVzc2lvbmFsfGVufDF8fHx8MTc3Mzg0MDg4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.6,
    type: 'request',
    createdAt: '2026-03-16',
  },
  {
    id: 'listing-4',
    title: 'Professional Photography & Editing',
    description: 'Master DSLR photography, composition, lighting, and Adobe Lightroom/Photoshop editing.',
    category: 'Creative',
    price: 50,
    swapAvailable: false,
    userId: 'user-5',
    userName: 'James Kim',
    userAvatar: 'https://images.unsplash.com/photo-1738566061688-47e66a008254?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHByb2Zlc3Npb25hbCUyMGJ1c2luZXNzJTIwcGVyc29ufGVufDF8fHx8MTc3MzkzMzMzMHww&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 5.0,
    type: 'offer',
    createdAt: '2026-03-15',
  },
  {
    id: 'listing-5',
    title: 'Digital Marketing & SEO Strategy',
    description: 'Learn social media marketing, Google Ads, SEO optimization, and content marketing strategies.',
    category: 'Business',
    price: 40,
    swapAvailable: true,
    userId: 'user-2',
    userName: 'Sarah Chen',
    userAvatar: 'https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwcHJvZmVzc2lvbmFsJTIwaGVhZHNob3R8ZW58MXx8fHwxNzczODM2NjU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.9,
    type: 'offer',
    createdAt: '2026-03-14',
  },
  {
    id: 'listing-6',
    title: 'Looking for Piano Instructor',
    description: 'Complete beginner looking to learn piano. Can offer web development lessons in exchange.',
    category: 'Music',
    swapAvailable: true,
    userId: 'user-6',
    userName: 'David Park',
    userAvatar: 'https://images.unsplash.com/photo-1655249481446-25d575f1c054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBidXNpbmVzcyUyMHBlcnNvbiUyMHBvcnRyYWl0fGVufDF8fHx8MTc3MzgyODg4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.5,
    type: 'request',
    createdAt: '2026-03-13',
  },
  {
    id: 'listing-7',
    title: 'Yoga & Meditation Classes',
    description: 'Hatha yoga, meditation techniques, and mindfulness practices for all levels.',
    category: 'Health & Fitness',
    price: 25,
    swapAvailable: true,
    userId: 'user-4',
    userName: 'Emma Rodriguez',
    userAvatar: 'https://images.unsplash.com/photo-1687575635557-a3f3ed535b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGNyZWF0aXZlJTIwcHJvZmVzc2lvbmFsfGVufDF8fHx8MTc3Mzg0MDg4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.6,
    type: 'offer',
    createdAt: '2026-03-12',
  },
  {
    id: 'listing-8',
    title: 'Data Science & Machine Learning',
    description: 'Python for data science, pandas, scikit-learn, and intro to neural networks.',
    category: 'Programming',
    price: 55,
    swapAvailable: false,
    userId: 'user-3',
    userName: 'Michael Torres',
    userAvatar: 'https://images.unsplash.com/photo-1605298046196-e205d0d699d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHNtaWxpbmd8ZW58MXx8fHwxNzczOTMyNjIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    userRating: 4.7,
    type: 'offer',
    createdAt: '2026-03-11',
  },
];

export const upcomingSessions: Session[] = [
  {
    id: 'session-1',
    skillTitle: 'Advanced React Patterns',
    otherUser: 'Sarah Chen',
    otherUserAvatar: 'https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwcHJvZmVzc2lvbmFsJTIwaGVhZHNob3R8ZW58MXx8fHwxNzczODM2NjU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    date: '2026-03-22',
    time: '14:00',
    status: 'upcoming',
    type: 'learning',
  },
  {
    id: 'session-2',
    skillTitle: 'Python Development',
    otherUser: 'Emma Rodriguez',
    otherUserAvatar: 'https://images.unsplash.com/photo-1687575635557-a3f3ed535b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGNyZWF0aXZlJTIwcHJvZmVzc2lvbmFsfGVufDF8fHx8MTc3Mzg0MDg4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    date: '2026-03-24',
    time: '10:00',
    status: 'upcoming',
    type: 'teaching',
  },
  {
    id: 'session-3',
    skillTitle: 'Guitar Basics',
    otherUser: 'Michael Torres',
    otherUserAvatar: 'https://images.unsplash.com/photo-1605298046196-e205d0d699d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHNtaWxpbmd8ZW58MXx8fHwxNzczOTMyNjIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    date: '2026-03-26',
    time: '16:30',
    status: 'upcoming',
    type: 'learning',
  },
];

export const userReviews: Review[] = [
  {
    id: 'review-1',
    fromUser: 'Emma Rodriguez',
    fromUserAvatar: 'https://images.unsplash.com/photo-1687575635557-a3f3ed535b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGNyZWF0aXZlJTIwcHJvZmVzc2lvbmFsfGVufDF8fHx8MTc3Mzg0MDg4OXww&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 5,
    comment: 'Alex is an excellent teacher! Very patient and explains complex concepts in a simple way. Highly recommend!',
    date: '2026-03-10',
    skillTitle: 'Python Programming',
  },
  {
    id: 'review-2',
    fromUser: 'Michael Torres',
    fromUserAvatar: 'https://images.unsplash.com/photo-1605298046196-e205d0d699d7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYW4lMjBwcm9mZXNzaW9uYWwlMjBwb3J0cmFpdCUyMHNtaWxpbmd8ZW58MXx8fHwxNzczOTMyNjIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 5,
    comment: 'Great session on React hooks and state management. Alex really knows his stuff!',
    date: '2026-03-05',
    skillTitle: 'React Development',
  },
  {
    id: 'review-3',
    fromUser: 'Sarah Chen',
    fromUserAvatar: 'https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMHdvbWFuJTIwcHJvZmVzc2lvbmFsJTIwaGVhZHNob3R8ZW58MXx8fHwxNzczODM2NjU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    rating: 4,
    comment: 'Very knowledgeable and professional. Would love to have more sessions!',
    date: '2026-02-28',
    skillTitle: 'UI/UX Design',
  },
];

export const categories = [
  'All',
  'Programming',
  'Design',
  'Business',
  'Music',
  'Languages',
  'Health & Fitness',
  'Creative',
];
